name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      uses: docker/login-action@v3.3.0
      with:
          # Server address of Docker registry. If not set then will default to Docker Hub
       #registry: # optional
    # Username used to log against the Docker registry
       username: ${{ secrets.DOCKER_USERNAME }}
    # Password or personal access token used to log against the Docker registry
       password: ${{ secrets.DOCKER_PASS }}
    # Specifies whether the given registry is ECR (auto, true or false)
    #ecr: # optional, default is auto
    # Log out from the Docker registry at the end of a job
    #logout: # optional, default is true
          
    - uses: actions/checkout@v4
    - name: Fetch release version
      id: fetch-release
      run: |
          curl -sL https://api.github.com/repos/pi-hole/docker-pi-hole/releases/latest | \
          jq -r ".tag_name" > one-container/pihole-unbound/VERSION
    - name: Check for modified files
      id: git-check
      run: |
          echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
          echo ::set-output name=version::$(cat one-container/pihole-unbound/VERSION)
    # - name: Commit latest release version
    #   if: steps.git-check.outputs.modified == 'true'
    #   run: |
    #       git config --global user.name 'Amr ElRefaie'
    #       git config --global user.email 'amour86@users.noreply.github.com'
    #       git commit -am "New release version on ${{ steps.fetch-release.outputs.version }}"
    #       git push
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
          commit-message: Update PiHole to ${{ steps.git-check.outputs.version }}
          title: Update PiHole to ${{ steps.git-check.outputs.version }}
          body: |
            Hi @amour86,
                  Updates [pi-hole][1] to ${{ steps.git-check.outputs.version }}

            Auto-generated by [create-pull-request][2]

            [1]: https://github.com/pi-hole/pi-hole
            [2]: https://github.com/peter-evans/create-pull-request
          labels: new release, automated pr
          branch: pi-hole-updates
    # - name: Build the Docker image
    #   run: |
    #       PIHOLE_VER=`cat one-container/pihole-unbound/VERSION`
    #       docker buildx build --file one-container/pihole-unbound/Dockerfile  --build-arg PIHOLE_VERSION=$PIHOLE_VER --platform linux/amd64 -t amour86/pihole-unbound:latesttest --push .
